version: '3.8'

services:
  playwright:
    container_name: playwrightapi  
    build:
      context: ..  
      dockerfile: .devcontainer/dockerfile  #
    volumes:
      - ..:/workspace
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=${DISPLAY}
      - NVM_DIR=/root/.nvm
    ports:
      - "3001:3001"
    command: /bin/bash -c "sleep infinity"
    tty: true